# Generated by Django 3.2.7 on 2022-03-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UssdApp', '0003_session_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
