# Generated by Django 3.2.7 on 2022-03-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UssdApp', '0004_user_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='secondNumber',
            new_name='secondName',
        ),
    ]
